const recipes = [
  {
    name: "Moqueca de peixe",
    type: "Peixe",
    imageUrl:
      "https://drive.google.com/uc?id=1rroL4uLJJhyHpeqBXS-Im93ok2Dp2ysX",
    preparationTime: "70min",
    portions: 4,
    level: "Medio",
    ingredients: [
      "4postas de cação ou garoupa (700 gramas)",
      "suco de 1 limão",
      "1 cebola grande cortada em rodelas",
      "1 pimentão vermelho cortado em rodelas",
      "1 pimentão verde cortado em rodelas",
      "2 tomates maduros cortados em rodelas",
      "2 colheres (sopa) de coentro",
      "200 ml de leite de coco",
      "1 colher (sopa) de azeite de dendê",
      "2 tabletes de caldo de camarão",
    ],
    preparationMethod: [
      "Lave bem o peixe, regue com o suco de limão e deixe descansar por cerca de 1 hora.",
      "Em uma panela grande, coloque o peixe, a cebola, os pimentões, os tomates e polvilhe coentro.",
      "Esfarele os tabletes de caldo de camarão, misture-os ao leite de coco e regue o peixe.",
      "Leve ao fogo baixo, com a panela parcialmente tampada, por 20 minutos.",
      "Mexa algumas vezes até que esteja cozido.",
      "Junte o azeite de dendê e adicione sal.",
      "Retire do fogo e sirva.",
    ],
  },
  {
    name: "Paella de frutos do mar",
    type: "Peixe",
    imageUrl:
      "https://drive.google.com/uc?id=1VMU8_M-7EjTNWrct2RhXx3-xNUixqi_d",
    preparation_time: "45min",
    level: "Medio",
    portions: 4,
    ingredients: [
      "2 xícaras de arroz arbóreo ou arroz para paella",
      "4 xícaras de caldo de camarão",
      "500 gramas de lula",
      "500 gramas de camarão fresco (dos grandes, com cabeça)",
      "1 xícara de conchas e mexilhões (a gosto)",
      "1 cebola",
      "1 tomate médio",
      "Meio pimentão vermelho",
      "2 dentes de alho grandes",
      "Meia xícara de ervilha (se for congelada, cuidado com o excesso de água)",
      "Um pouco de salsinha fresca picada",
      "Azeite de oliva extra virgem",
      "Sal, pimenta e açafrão a gosto",
    ],
    preparationMethod: [
      "Limpe os camarões e reserve as cabeças e as carcaças. Faça um caldo deixando ferver em 4 xícaras de água. Coe e guarde o caldo.",
      "Limpe e corte as lulas em rodelas.",
      "Lave as conchas e mexilhões com bastante água.",
      "Coloque azeite na paellera e frite o alho, a cebola, o pimentão e o tomate. Adicione sal e pimenta a gosto.",
      "Em seguida coloque as lulas, os mexilhões e as conchas para que cozinhem durante alguns minutos.",
      "Adicione o arroz e mexa para que se espalhe de maneira uniforme. Coloque o caldo do camarão e mexa bem. Adicione o açafrão.",
      "Agora é hora de adicionar as ervilhas, os camarões e a salsinha. Acerte o tempero.",
      "Deixe cozinhar até que o caldo esteja quse seco. Abaixe o fogo, tampe e deixe cozinhar por 15 minutos.",
      "Sirva com limão para dar um gosto ainda melhor!",
    ],
  },
  {
    name: "Costela de tira com amendoim caramelizado",
    type: "Carne",
    imageUrl:
      "https://drive.google.com/uc?id=1ZjOeGZyfAyal6AOMlIZNdYawPa5OwFtI",
    preparation_time: "45min",
    level: "Dificil",
    portions: 4,
    ingredients: [
      "4 assados de tira",
      "1 acelga",
      "1 abacaxi",
      "3 cenouras",
      "1 pimenta dedo de moça",
      "1 colher de chá de gengibre",
      "1 dente de alho",
      "Meia xícara de mel",
      "Meia xícara de shoyu",
      "1 limão verde",
      "1 limão siciliano",
      "1 limão cravo",
      "1 laranja bahia",
      "1 dente de alho",
      "3 talos de cebolinha",
      "1 xícara de amendoim",
      "1 colher de sobremesa de açúcar mascavo",
      "1 colher de chá de páprica picante",
      "1 colher de chá de cominho",
      "1 punhado de salsa",
    ],
    preparationMethod: [
      "Corte as acelgas ao meio no sentido do comprimento e retire as cascas do abacaxi e da cenoura",
      "Passe azeite em tudo e leve para a brasa junto com uma pimenta dedo de moça pra que tostem",
      "Retire tudo da brasa e corte os legumes cenoura em cortes diagonais, acelga em cortes grosseiros e abacaxi em cubos.",
      "Faça o molho num bowl, coloque a dedo de moça picada, o alho e o gengibre ralados, o mel, o shoyu, os sucos dos limões e da laranja e misture bem",
      "Leve os assados de tira com sal para a grelha e deixe grelhar. Leve os legumes e o abacaxi a uma panela com um fio de azeite e adicione o molho. Misture e deixe caramelizar um pouco. Adicione as cebolinhas na brasa para uma rápida tosta e retire tudo do fogo.",
      "Passe o dente de alho na carne e coloque as cebolinhas por cima . Numa assadeira perfurada, coloque o amendoim, o açúcar mascavo e as especiarias e leve ao fogo direto para uma rápida tosta. Coloque por cima dos vegetais glaceados e finalize com a salsa rasgada.",
    ],
  },
  {
    name: "Fraldinha na cerveja",
    type: "Carne",
    imageUrl:
      "https://drive.google.com/uc?id=1uSK3EHhz6fZRsNnWFwcF7utJ3QXRdNR6",
    preparation_time: "2h 45min",
    level: "Facil",
    portions: 4,
    ingredients: [
      "1 peça de fraldinha com cerca de 1 kg",
      "350 ml de cerveja escura (1 lata)",
      "2 cebolas",
      "2 pimentões vermelhos",
      "3 dentes de alho",
      "2 colheres (sopa) de açúcar mascavo",
      "2 colheres (sopa) de extrato de tomate",
      "1 colher (sopa) de vinagre de vinho tinto",
      "6 ramos de tomilho",
      "2 colheres (sopa) de azeite",
      "sal e pimenta-do-reino moída na hora a gosto",
    ],
    preparationMethod: [
      "Corte as acelgas ao meio no sentido do comprimento e retire as cascas do abacaxi e da cenoura",
      "Passe azeite em tudo e leve para a brasa junto com uma pimenta dedo de moça pra que tostem",
      "Retire tudo da brasa e corte os legumes cenoura em cortes diagonais, acelga em cortes grosseiros e abacaxi em cubos.",
      "Faça o molho num bowl, coloque a dedo de moça picada, o alho e o gengibre ralados, o mel, o shoyu, os sucos dos limões e da laranja e misture bem",
      "Leve os assados de tira com sal para a grelha e deixe grelhar. Leve os legumes e o abacaxi a uma panela com um fio de azeite e adicione o molho. Misture e deixe caramelizar um pouco. Adicione as cebolinhas na brasa para uma rápida tosta e retire tudo do fogo.",
      "Passe o dente de alho na carne e coloque as cebolinhas por cima . Numa assadeira perfurada, coloque o amendoim, o açúcar mascavo e as especiarias e leve ao fogo direto para uma rápida tosta. Coloque por cima dos vegetais glaceados e finalize com a salsa rasgada.",
    ],
  },
  {
    name: "Frango À Grega",
    type: "Frango",
    imageUrl:
      "https://drive.google.com/uc?id=1WkNe4TeGGXwyWt-rkheBGTqkAZCiZcP_",
    preparation_time: "40min",
    level: "Facil",
    portions: 4,
    ingredients: [
      "1kb de peito de frango",
      "4 colheres (sopa) de azeite",
      "1 cebola fatiada finamente",
      "4 dentes de alho picados",
      "1 cenoura levemente cozida e cortada em cubos",
      "500g de tomates",
      "2 pimentões amarelo e vermelho cortados em cubos",
      "Canela em pó",
      "1 colher (chá) de orégano",
      "1 pimenta dedo-de-moça",
      "150ml de caldo de galinha",
      "Salsa picada",
      "Pimenta-do-reino",
    ],
    preparationMethod: [
      "Corte o frango em cubos e tempere com a canela em pó.",
      "Refogue até dourar e acrescente os outros ingredientes. Mexa bem e deixe cozinhar.",
      "Ajuste o tempero e sirva com arroz ou purê.",
    ],
  },
  {
    name: "Frango Assado com Salsa e Cebolinha Verde",
    type: "Frango",
    imageUrl:
      "https://drive.google.com/uc?id=1dVEBrw3m0NqkaIGyfM6p3hhnlhizXdwK",
    preparation_time: "2h",
    level: "Dificil",
    portions: 10,
    ingredients: [
      "1 frango inteiro limpo (1,5kg)",
      "2 colheres (sopa) de manteiga",
      "2 colheres (chá) de sal",
      "3 dentes de alho amassados",
      "2 colheres (sopa) de vinagre de maçã",
      "1 colher (chá) de Pimenta-do-Reino Preta Moída",
      "2 colheres (chá) de Salsa",
      "2 colheres (chá) de Cebolinha Verde",
    ],
    preparationMethod: [
      "Pré-aqueça o forno em temperatura média (180ºC).",
      "Em uma assadeira, coloque o frango e faça alguns furos com auxílio de um garfo.",
      "Reserve.",
      "Em uma tigela, misture a manteiga, o sal, o alho, o vinagre, a Pimenta-do-Reino Preta Moída, a Salsa e a Cebolinha Verde.",
      "Espalhe a mistura dentro e fora do frango reservado",
      "Cubra com papel-alumínio. Leve ao forno por 40 minutos.",
      "Retire o papel-alumínio e leve ao forno por mais 40 minutos, regando com o caldo da assadeira de vez em quando até dourar e o caldo reduzir. Sirva em seguida.",
    ],
  },
  {
    name: "Bochecha de porco pururucada com laranja",
    type: "Porco",
    imageUrl:
      "https://drive.google.com/uc?id=1PInH51yCkXj3HFkmOQBIokbZE1L1--7t",
    preparation_time: "1h 20min",
    level: "Medio",
    portions: 2,
    ingredients: [
      "1 unidade Bochecha porco",
      "1 unidade Laranja",
      "2 unidades Cravo da índia",
      "4 bagas Zimbro",
      "1 colher para sopa Açúcar mascavo",
      "1 colher para café Cominho em pó",
      "1 colher para café Sal",
      "PARA PURURUCAR",
      "500ml Óleo de soja",
    ],
    preparationMethod: [
      "Limpe a bochecha retirando o excesso de gordura e as glândulas (círculos de gordura quase transparentes). Se preferir peça ao seu açougueiro para limpar. Uma vez limpa, remova as aparas laterais para que fique com o formato retangular.",
      "Faça cortes paralelos na pele da bochecha até chegar na gordura. Inicie com cortes horizontais e depois faça cortes verticais para que fique como uma tabuleiro de xadrez.",
      "Deixe marinar por 24 horas, para isso coloque a bochecha em um saco ou uma vasilha com o suco de laranja e demais ingredientes.",
      "Leve para assar por 1 hora coberto por papel alumínio em forno pré-aquecido a 200°c.",
      "Para pururucar a bochecha aqueça 500ml de óleo de soja, deixe bem quente. Retire a bochecha do forno e coloque sobre um escorredor de macarrão encaixado em uma panela funda. Passe cachaça na pele da bochecha e em seguida despeje o óleo de soja bem quente sobre a pele. Despeje devagar. Começarão a surgir bolhas na pele que ficará pururucada. Sirva em seguida com batatas ao murro ou como um aperitivo",
    ],
  },
  {
    name: "Lombo de porco com laranja e alecrim",
    type: "Porco",
    imageUrl:
      "https://drive.google.com/uc?id=1bWu4e2YRXojx6hWxffMAQraQ2ey290m2",
    preparation_time: "35h",
    level: "Dificil",
    portions: 10,
    ingredients: [
      "1 xícara de suco de laranja;",
      "1 colher de sopa de mel;",
      "2 colheres de sopa de azeite;",
      "Meia cabeça de alho;",
      "Meia xícara de alecrim fresco;",
      "Sal e pimenta do reino moída na hora a gosto.",
      "Corte de lombo de porco de aproximadamente 2kg",
    ],
    preparationMethod: [
      "Comece processando o suco de laranja, com o mel, azeite, o alho e sal e pimenta do reino moída na hora a gosto até formar uma pasta.",
      "Adicione a essa mistura o alecrim fresco;",
      "Logo após, faça alguns furos na carne, passe a pasta que se formou com os temperos e deixe na geladeira de um dia para o outro;",
      "Para assar, leve ao forno em temperatura alta e pré-aquecido durante 1h com o tabuleiro coberto com papel alumínio.",
      "Depois desse tempo, retire o papel e deixe ficar ficar bem dourado, virando a carne para não ficar branquela por baixo",
      "É importante que você vá adicionando água quente ao tabuleiro caso ele vá secando e que abra o forno de vez em quando para regar a carne;",
      "Se você quiser tirar a dúvida do ponto da sua carne e não tiver por aí um termômetro culinário, a minha dica é fazer um corte bem no meio do pedaço de carne, assim você já vê como está o seu assado e ainda consegue cortar bem em fatias.",
    ],
  },
  {
    name: "Tiramisu",
    type: "Sobremesa",
    imageUrl:
      "https://drive.google.com/uc?id=1tTcRe3oPXcnvzeYnTrGOmyZvuAzth2KP",
    preparation_time: "30min",
    level: "Facil",
    portions: 10,
    ingredients: [
      "1 pacote de biscoitos champangne",
      "500 g de queijo mascarpone (pode substituir com 500 g de requeijão cremoso tipo catupiry)",
      "250 ml de creme de leite fresco",
      "3 gemas",
      "150 g de açúcar",
      "1 cálice de conhaque (opcional)",
      "2 xícaras de café frio",
      "chocolate em pó",
    ],
    preparationMethod: [
      "Bata o creme de leite na batedeira até obter um chantilly firme.",
      "Reserve.",
      "Bata o açúcar com as gemas e o conhaque por 3 minutos.",
      "Acrescente o chantilly, o mascarpone e misture bem.",
      "Montagem",
      "Molhe rapidamente os biscoitos no café (um a um) e coloque em um refratário formando uma camada, coloque por cima uma camada do creme, faça mais uma camada de biscoitos molhados no café e por último mais uma camada de creme.",
      "Para finalizar polvilhe chocolate em pó amargo.",
      "Leve à geladeira por no mínimo 3 horas e sirva.",
    ],
  },
  {
    name: "Bolinho de chuva",
    type: "Sobremesa",
    imageUrl:
      "https://drive.google.com/uc?id=1XFwUa3C9WbeY6EJKJMoiw0KdP8IcxRNb",
    preparation_time: "30min",
    level: "Facil",
    portions: 10,
    ingredients: [
      "3 xícaras de farinha de trigo",
      "2 colheres (sopa) de açúcar",
      "Uma pitada de sal",
      "1 colher (sopa) de fermento químico em pó",
      "2 colheres (sopa) de manteiga",
      "Raspas da casca de 1 limão",
      "1 xícara de leite",
      "1 ovo",
    ],
    preparationMethod: [
      "Em uma tigela grande, junte a farinha, o açúcar, o sal, o fermento, a manteiga e as raspas de limão. Misture bem.",
      "Junte o ovo e o leite, aos poucos, mexendo sempre com uma colher de pau.",
      "Deixe a massa descansar por 15 minutos.",
      "Depois, pegue colheradas da massa e frite em óleo quente.",
      "Escorra os bolinhos em papel-toalha e, em seguida, polvilhe-os com açúcar e canela.",
    ],
  },
];

// PARA SALVAR AS IMAGENS
// Redimencionar o tamanho das imagens para 200 KB
// Salvar imagens no Drive
// Ao pegar o link da imagem no Drive
// Trocar o file para uc?id= e tirar o view do final da url

export default recipes;
